name: fyp2_system
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.1
  flutter_svg: ^2.0.0+1
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  flutter_iconly: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  fluttertoast: ^8.1.2
  shared_preferences: ^2.0.17
  provider: ^6.0.5
  syncfusion_flutter_charts: ^20.4.44
  flutter_native_splash: ^2.2.17
  cloud_firestore: ^4.4.2
  firebase_storage: ^11.0.10
  image_picker: ^0.8.6+4
  cached_network_image: ^3.2.3
  shimmer_animation: ^2.1.0+1
  fancy_shimmer_image: ^2.0.2
  flutter_staggered_grid_view: ^0.6.2
  badges: ^3.0.2
  card_swiper: ^2.0.4
  flutter_spinkit: ^5.1.0
  google_sign_in: ^6.0.1
  file_picker: ^5.2.5
  get: ^4.6.5
  csc_picker: ^0.2.7
  country_state_city_picker: ^1.2.8
  uuid: ^3.0.7
  flutter_stripe: ^8.0.0+1
  http: ^0.13.5
  flutter_local_notifications: ^13.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
   - lib/assets/images/
   - lib/assets/svgs/

 
  fonts:
     - family: Brand-Bold
       fonts:
         - asset: lib/assets/fonts/GemunuLibre-Bold.ttf


     - family: Semi-Bold
       fonts:
         - asset: lib/assets/fonts/GemunuLibre-SemiBold.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
