// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXgkSUl8-AZC-NzSui-RgjOoku9u_Idxk',
    appId: '1:688200263234:web:68bba29428659ed27befdb',
    messagingSenderId: '688200263234',
    projectId: 'telco-system-app',
    authDomain: 'telco-system-app.firebaseapp.com',
    databaseURL: 'https://telco-system-app-default-rtdb.firebaseio.com',
    storageBucket: 'telco-system-app.appspot.com',
    measurementId: 'G-YXX53KR6MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2EDVH9I_pytK0rmQaOSHeDlNcMv4EXvY',
    appId: '1:688200263234:android:5d0c430003e2a6537befdb',
    messagingSenderId: '688200263234',
    projectId: 'telco-system-app',
    databaseURL: 'https://telco-system-app-default-rtdb.firebaseio.com',
    storageBucket: 'telco-system-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWJdJcNwkl7auri3MvFsHwT_DeqIVE7eE',
    appId: '1:688200263234:ios:60578308057381a77befdb',
    messagingSenderId: '688200263234',
    projectId: 'telco-system-app',
    databaseURL: 'https://telco-system-app-default-rtdb.firebaseio.com',
    storageBucket: 'telco-system-app.appspot.com',
    iosClientId: '688200263234-eeepq67ctvgfug81b8c24uj953o0oapk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp2System',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWJdJcNwkl7auri3MvFsHwT_DeqIVE7eE',
    appId: '1:688200263234:ios:60578308057381a77befdb',
    messagingSenderId: '688200263234',
    projectId: 'telco-system-app',
    databaseURL: 'https://telco-system-app-default-rtdb.firebaseio.com',
    storageBucket: 'telco-system-app.appspot.com',
    iosClientId: '688200263234-eeepq67ctvgfug81b8c24uj953o0oapk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp2System',
  );
}
